### ISSUE TITLE
should it work on supercard ?

### ISSUE THREAD

**Issue by PhieF** [NuVanDibe/Pogoshell-K#2]
Hi !

Thank you for your work !

I was trying it on my GBA with a supercard, when loading both gba file my screen stays black with a strange blank noise, is it meant to be run on a supercard ?

Thanks !

**Comment by NuVanDibe** [comment]
I doubt it. I believe Pogoshell really only works fully with Visoly and Xrom flash carts.

Also, I should point out that this is an archive of someone else's work who passed away. Check the first section of the readme for more info.
